// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQhawA8gNeA3mw_PEfLJJbO040TjulGY',
    appId: '1:459699834681:web:7564416813cb7fa7ed62e8',
    messagingSenderId: '459699834681',
    projectId: 'authdemo-c26c3',
    authDomain: 'authdemo-c26c3.firebaseapp.com',
    storageBucket: 'authdemo-c26c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpsvfC_bxEEzwkcQR_JUgfbn3ON1N6Aa0',
    appId: '1:459699834681:android:b5188c407fde2664ed62e8',
    messagingSenderId: '459699834681',
    projectId: 'authdemo-c26c3',
    storageBucket: 'authdemo-c26c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVt7dyl5IrAReXjaSaygCq1NzEYIhzOIk',
    appId: '1:459699834681:ios:1b8ab6947fd2a9f1ed62e8',
    messagingSenderId: '459699834681',
    projectId: 'authdemo-c26c3',
    storageBucket: 'authdemo-c26c3.appspot.com',
    iosClientId: '459699834681-oitje5gc34gei2hrbeg1tl8rc3dbnke2.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVt7dyl5IrAReXjaSaygCq1NzEYIhzOIk',
    appId: '1:459699834681:ios:1b8ab6947fd2a9f1ed62e8',
    messagingSenderId: '459699834681',
    projectId: 'authdemo-c26c3',
    storageBucket: 'authdemo-c26c3.appspot.com',
    iosClientId: '459699834681-oitje5gc34gei2hrbeg1tl8rc3dbnke2.apps.googleusercontent.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVQhawA8gNeA3mw_PEfLJJbO040TjulGY',
    appId: '1:459699834681:web:2957ae6b05889eabed62e8',
    messagingSenderId: '459699834681',
    projectId: 'authdemo-c26c3',
    authDomain: 'authdemo-c26c3.firebaseapp.com',
    storageBucket: 'authdemo-c26c3.appspot.com',
  );

}